### ISSUE TITLE
Publish commonJS modules

### ISSUE THREAD

**Issue by mariusGundersen** [desko27/react-call#6]
I prefer ES modules, but unfortunately I can't use them in my current project, because react only has commonJS exports. Can you publish the package containing both ESM and CJS modules? That way I can use it in my project.

**Comment by desko27** [comment]
Hi @mariusGundersen, thanks for you request.

It has been a long time since I had to deal with CJS so I wasn't actually planning on adding support for it. Although I can understand some of you can't choose.

I think #8 should do but I'm not sure how to test it, especially TypeScript types. Are you using some sort of webpack/babel setup? I've published `react-call@next` as a pre-release for testing purposes. Could you please give it a try and let me know?

**Comment by mariusGundersen** [comment]
For my scenario I'm doing no bundling or transpilation, that is part of the problem. If I did transpile then maybe it would work. I will give it a try on Monday, when I'm back to work
